### ISSUE TITLE
Feature Request - Option to export Prometheus metrics for node_exporter

### ISSUE THREAD

**Issue by oijkn** [hyperjumptech/monika#1025]
Hello Monika team,

I'm using Monika, and I've found it to be a very useful tool for synthetic monitoring. However, I noticed that there isn't an option to export Prometheus metrics for **node_exporter**. I would like to request that this feature be added to Monika.

We could then use these metrics to create dashboards in Grafana or other monitoring tools.

I suggest that this feature should allow us to specify a file path where the Prometheus metrics can be written to in the **.prom** format. This would make it easier to integrate Monika with our existing monitoring infrastructure.

I hope you will consider adding this feature to Monika. Thank you for your consideration.

Best regards.

**Comment by sapiderman** [comment]
@oijkn thanks for the issue, we'll look into it.

**Comment by nicnocquee** [comment]
Unfortunately we don't have bandwidth to work on this. Please open PR if you want it to be added to Monika.
