### ISSUE TITLE
POST payload data inside yaml config

### ISSUE THREAD

**Issue by luizrojo** [hyperjumptech/monika#1045]
Reading through the documentation, I could not find an example to add the request body directly in the config file.

Is this possible? What would be the best approach for that?

**Comment by sapiderman** [comment]
hi @luizrojo 

Can you please check https://monika.hyperjump.tech/guides/examples#requests-chaining
Let me know if this doesn't answer your question.

**Comment by sapiderman** [comment]
Closing this. Improved the documentation to better highlight body payloads in pr #1048

**Comment by luizrojo** [comment]
@sapiderman The idea was to be able to add an actual payload, like XML, YAML, or JSON, directly on the config file.

The ability to reference the payload from a file would be even nicer, since one could use a config management system to template payloads and deliver them through automation.

**Comment by sapiderman** [comment]
@luizrojo Oooh thanks for the input, that's an nteresting feature. We'll keep this in mind, mull over how to implement this and argue its use cases.
