### ISSUE TITLE
No messages received on WhatsApp

### ISSUE THREAD

**Issue by abhijitjaiswal** [hyperjumptech/monika#1050]
### Discussed in https://github.com/hyperjumptech/monika/discussions/1049

<div type='discussions-op-text'>

<sup>Originally posted by **abhijitjaiswal** May 23, 2023</sup>
Hi, I didn't receive any message on WhatsApp the I tried registering my mobile number here: when signed up at https://whatsapp.hyperjump.tech/?tab=register 
Can somebody help here ?</div>

**Comment by sapiderman** [comment]
thanks @abhijitjaiswal  we'll look into it

**Comment by sapiderman** [comment]
As it seems to be an issue with a specifc mobile number, will be closing this issue.
