### ISSUE TITLE
Monika sends two notification for one incident

### ISSUE THREAD

**Issue by haricnugraha** [hyperjumptech/monika#1060]
**Describe the bug**
Monika sends two notification for one incident when using default alert. Probably also happens to custom alert that has more than one alert, I haven't tested it. 

**To Reproduce**
1. Run local server
2. Run Monika that probe the local server with default alert
3. Stop the local server

**Expected behavior**
Monika sends only one notification

**Videos**

https://github.com/hyperjumptech/monika/assets/15191978/01339e56-615c-4085-b72f-7e48057d1e36

**Desktop (please complete the following information):**
 - OS: [e.g. Pop!_OS]
 - Version [e.g. 22.04]
 - Monika version: main branch

**Comment by arshadmech** [comment]
Webhook notification is not working in latest release. v1.6. please find below and help me resolving

 ›   Error: Failed to send message using Webhook, please check your Webhook notification config.
 ›   Message: Request failed with status code 400
