### ISSUE TITLE
i am getting 99 as a error code for my application, when i ran the monika -c monika.yaml

### ISSUE THREAD

**Issue by arshadmech** [hyperjumptech/monika#1132]
Hi
This is Syed Arshad
i configured a monika.yaml file for monitoring my application, When i run "monika -c monika.yaml" command, i am getting error 99, but actually my application is running. 
i checked error 99 in google i got this " Response Code 99 indicates that the payment gateway could not authenticate the transaction fingerprint submitted for a Server Integration Method (SIM) transaction."

Please find my yaml file below....
probes:
  - id: 'swd'
    name: qw
    requests:
      - url: https://xyz
        body: {}
        timeout: 30000
        alerts:
           - assertion: response.status != 200
             message: Application server is stopped
    incidentThreshold: 6
    recoveryThreshold: 6
notifications:
  - id: myGoogleChatNotif
    type: google-chat
    data:
      url: https://chat.googleapis.com/v1/......
      
      
  Please find the error below
  id:swd 99 GET https://xyz 81ms, ALERT: response.status != 200
  
  Can you help me in this

**Comment by sapiderman** [comment]
Hi Syed,

An error code '99' in our case signify an "unknown http request error".  It is a low level (driver) error and not really comply to the standard http.status coding. We are using Axios for the http requests, and there are axios error that we mapped to  numbers 0 to 14, (14 is an 'ERR_INVALID_URL' error for instance). 99 is an unknown error.

Can you try using curl: `curl  -vv -X GET https://xyz` and see wht status code you are actually getting?

Thanks.

**Comment by arshadmech** [comment]
Hi sapiderman
1 . Can you try using curl: curl  -vv -X GET https://xyz and see wht status code you are actually getting?
Answer: where i need to add this.Please tell me.
2. Are you using https? Are you sure it is https and not http?
Answer: Yes i am using https

**Comment by arshadmech** [comment]
Hi sapiderman,
1 . Can you try using curl: curl -vv -X GET https://xyz/ and see wht status code you are actually getting?
Answer: i executed curl command in terminal (linux), it is working for me.
curl --vv-X GET https://xyz/               (working for me in linux terminal) but in monika.yaml file i am getting error 99

**Comment by sapiderman** [comment]
hmm interesting, @arshadmech 

I'm curious as what http response you are getting. 

Would you mind posting here the response to this `curl -w "http.code: %{http_code}" https://<your application here>.`
(note the w switch `-w`,  and curly braces)

thanks

**Comment by arshadmech** [comment]
Hi @sapiderman 

please find the below Screenshot of above command (result).
Can i use curl command in yaml file or any parameters for url....
					$.ajax({
						url: "user/registerNewUser"
						, type: "POST"
						, data: JSON.stringify(userObj)
						, contentType: "application/json; charset=utf-8"
						, dataType: "json"
						, success: function (data) {
							loadnewpage(email, pswd)
						}
					});
				}
			</script> -->

			</html>
http.code: 200
<img width="419" alt="image" src="https://github.com/hyperjumptech/monika/assets/77534698/cc32e79d-47f0-40d5-9ff2-4ef362d5e3c6">

**Comment by arshadmech** [comment]
Hi @sapiderman 

Any update...

Hi Team, can anyone help me on this?

**Comment by sapiderman** [comment]
Hi @arshadmech,

would it make any difference if you hit with monika using http instead of https? Do you get a different result than http.status = 99?

**Comment by arshadmech** [comment]
Hi @sapiderman 
i am getting same error with http also. Is there a way to use curl or using certificates(ca cert) or any other way......Please let me know
<img width="384" alt="image" src="https://github.com/hyperjumptech/monika/assets/77534698/46083778-baa8-41cd-afc0-233edbf7c0d0">

**Comment by haricnugraha** [comment]
Have you tried adding `method: POST` in your Monika confguration? Seems like you send GET request instead of POST request.

```yaml
probes:
  - id: "swd"
    name: qw
    requests:
      - url: https://xyz
        method: POST
        body: {}
        timeout: 30000
    alerts:
      - assertion: response.status != 200
        message: Application server is stopped
```

**Comment by arshadmech** [comment]
Hi @haricnugraha 

i tried above but same error i am getting...
fyi, i added letsencrypt SSL certificate(i deployed my application in Azure kubernetes with ingress controller) for my application. 
So is there any way?, i can pass SSL certificate to my url in yaml file....???

**Comment by arshadmech** [comment]
Hi @haricnugraha and @sapiderman ,
i want to deploy monika in kubernetes, to check the above error exits or not...
for this can you please send me kubernetes deployment yaml file for it. i prepared yaml file but it is now working as expected(in monika.yaml, URL part is ignoring, it is not considering)

**Comment by arshadmech** [comment]
i am not getting url part...please find the screenshot of logs
<img width="395" alt="image" src="https://github.com/hyperjumptech/monika/assets/77534698/c446be40-ab9d-4d15-95a3-37d219a93c19">

**Comment by sapiderman** [comment]
hi @arshadmech, Ooh I'm afraid I can't help you too much with your issue in kubernetes. I have no idea your architecture and settings. But as an idea maybe, are you able to access the url using another method. Does curl work? does ping work fom within your kubernetes?

**Comment by sapiderman** [comment]
Hi @arshadmech, 
Just to followup, are you still getting 99 problems?

**Comment by sapiderman** [comment]
"I've got 99 problems, but Monika ain't one"
