### ISSUE TITLE
Make Node.js CI workflow fail fast

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#1169]
The job [prod_test_binary](https://github.com/hyperjumptech/monika/blob/a9316c6ddf8f133414e0d85e08b90969528220ee/.github/workflows/node.js.yml#L55) in Node.js CI workflow takes time which can waste time when some other jobs fail. It's better to cancel the whole workflow if one of the jobs fail.

Seems like we can use the cancel-action to achieve this as mentioned here https://github.com/orgs/community/discussions/38361#discussioncomment-6350816

**Comment by nrsysdev** [comment]
Resolved by #1170
