### ISSUE TITLE
Pack Tarball in Publish to Snapcraft Pipeline Error

### ISSUE THREAD

**Issue by haricnugraha** [hyperjumptech/monika#1206]
**Describe the bug**
Pack tarball error in [publish to Snapcraft pipeline](https://github.com/hyperjumptech/monika/actions/runs/7124850527/job/19399874880).

**Expected behavior**
Monika packed as tarball.

**Screenshots**
![image](https://github.com/hyperjumptech/monika/assets/15191978/90eaf1f1-8e01-4f19-a25a-5215d1e4fe96)

**Comment by haricnugraha** [comment]
Reopened because it has not been fixed yet. https://github.com/hyperjumptech/monika/actions/runs/7297246215/job/19886287976

**Comment by sapiderman** [comment]
new type of error

![image](https://github.com/hyperjumptech/monika/assets/964106/b6bff0b9-0185-4af9-a0dd-5215f340088d)

**Comment by sapiderman** [comment]
Publish success

![image](https://github.com/hyperjumptech/monika/assets/964106/e3496c2e-9739-4902-bd0f-5aed8d9f51da)
