### ISSUE TITLE
Update Axios

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#1225]
# Update Axios to version 1.6.x

Monika still using 0.27.0, a few generations old vs the current 1.6.x version

## Target 

1. Update axios to leverage all the new security patches (see references)
2. Include all the released bug fixes (see reference below)

## References:
1. [SNYK-JS-AXIOS-6032459](https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459)
3. [CVE 2023 45857](https://github.com/advisories/GHSA-wf5p-g6vw-rhxx)
4. [Official Axios release page](https://github.com/axios/axios/releases)

**Comment by dennypradipta** [comment]
I've already mentioned that in #1034 that if you upgrade Axios, it will break because of pkg. So, might want to rethink about this (or just replace axios for something else)

**Comment by sapiderman** [comment]
Sure. Might worth another look and move forward.

**Comment by sapiderman** [comment]
maybe closing this ticket in favor of native fetch from ticket #1227
