### ISSUE TITLE
Undici crash even when fetch is not used

### ISSUE THREAD

**Issue by syamsudotdev** [hyperjumptech/monika#1263]
**Describe the bug**
Running Monika with `--symonUrl <URL> --symonKey <UUID> --follow-redirects=5 --retryInitialDelayMs=150000 --ignoreInvalidTLS` will log errors from undici.

**To Reproduce**

1. `monika --symonUrl <URL> --symonKey <UUID> --follow-redirects=5 --retryInitialDelayMs=150000 --ignoreInvalidTLS`
2. See error in screenshot

**Expected behavior**
Running command mentioned above should not log undici errors, as Monika is not provided with `--native-fetch` flag. Thus not using node.js' fetch API and should not log undici errors.

**Screenshots**
![image](https://github.com/hyperjumptech/monika/assets/9563873/1f44541d-1d7c-4529-b563-04be5f4a7942)

**Desktop (please complete the following information):**

- OS: [e.g. Ubuntu]
- Version [e.g. 18.04]

**Additional context**

**Comment by dennypradipta** [comment]
Got this thought after waking up today: Maybe Monika v1.19.1 isn't running very well with Symon because Monika didn't catch this error, hence breaking the probing mechanism, causing Monika only reported few probes only.
