### ISSUE TITLE
Create a custom user agent for Monika 

### ISSUE THREAD

**Issue by dennypradipta** [hyperjumptech/monika#1292]
While monitoring some sites that use Cloudflare/LiteSpeed, there may be false incidents regarding Cloudflare anti-DDOS protection, which could return 403.

References:
https://betterstack.com/docs/uptime/frequently-asked-questions/#what-user-agent-does-uptime-use
https://betterstack.com/community/questions/whitelisting-better-stack-ip-cloudflare/

**Comment by sapiderman** [comment]
What should it be? Something like:

Monika Synthetic Monitoring Bot Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

**Comment by dennypradipta** [comment]
> What should it be? Something like:
> 
> Monika Synthetic Monitoring Bot Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

Precisely something what I had in mind.
