### ISSUE TITLE
Docker build fails on local machine

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#1301]
**Describe the bug**
The Docker build process seems to be broken.

**To Reproduce**

1. Clone the project
2. Issue a `npm run build -w --packages/notification/` to build dependencies packages
3. Issue a `npm ci` to pull dependencies
4.  Issue a `make docker` at the project root

**Expected behavior**
Docker build is expected to run until completed.

**Screenshots**
![image](https://github.com/hyperjumptech/monika/assets/964106/df3a5b75-b4cc-462c-bff3-7925f0786e3e)

**Desktop (please complete the following information):**

- OS: WSL2 (Ubuntu 24.04) under WIndows 11 and linux Ubuntu 22.04 LTS.
- Monika: from main branch commit: (d5564bf67a6ade81ec1efc2368b0e1a73188af84)
- Console where the commands are run on both OS is bash

Note:
1. Not seeing the error in the docker build pipeline

**Comment by dennypradipta** [comment]
This will be marked as close as this problem was solved by #1304
