### ISSUE TITLE
Notification crashes, if linux distribution is not recognized by getos

### ISSUE THREAD

**Issue by creffect** [hyperjumptech/monika#1322]
**Describe the bug**
My hoster has a dockerized linux system, which is not recognized by "getos". 

I get the error "No unique release file found!" and monika crashes, when a notification should be sent. 

The error occurs in the file

```
hyperjumptech/monika/lib/components/notification/alert-message.js
```
using the function "getLinuxDistro"

Could you please catch the error and ignore the distribution, if it occures? Thank you.

**Comment by dennypradipta** [comment]
Thank you for reporting the bug! I'll try to check it out

**Comment by dennypradipta** [comment]
@creffect I've made a PR for this, but you might need to wait. All I can suggest is that you run Monika in Docker so that it will be detected as Alpine Linux

**Comment by dennypradipta** [comment]
This should be fixedi in the newest version, could you verify @creffect ?

**Comment by creffect** [comment]
> This should be fixedi in the newest version, could you verify @creffect ?

Thank you, I will try this week!

**Comment by creffect** [comment]
@dennypradipta Thank you, it works perfectly!
