### ISSUE TITLE
Add suggestion for opening monika config generator page when running Monika the first time  

### ISSUE THREAD

**Issue by ilmiawan** [hyperjumptech/monika#143]
**Describe the bug**
Currently when we try to run Monika in the first time, there is an error state that there is missing configuration file and link to monika example.

**To Reproduce**
1. Go to empty directory
2. run `npx run @hyperjumptech/monika`
3. See error

**Expected behavior**
When first time Running and cannot find configuration, directly open monika config generator in local browser.

**Comment by newm4n** [comment]
Not only first time though. But every time configuration file not found.

**Comment by newm4n** [comment]
From Pak @ariya 

This is how Fossil did it.
https://fossil-scm.org/home/help?cmd=ui

This is how git did it. (although its read only)

```
git instaweb -httpd=webrick
```

**Comment by ariya** [comment]
`fish_config` is a fantastic prior-art: https://fishshell.com/docs/current/cmds/fish_config.html

**Comment by nicnocquee** [comment]
For first iteration, let's do this:

- [ ] When monika cannot find a configuration file, show the following message: 

```
Configuration file not found. By default, Monika looks for monika.json configuration file in the current directory. Otherwise, you can also specify a configuration file using -c flag as follows

monika -c <path_to_configuration_file>

You can create a configuration file via web interface by opening this web app: https://hyperjumptech.github.io/monika-config-generator/
```

- [ ] When monika is run with `--create-config` flag, open the browser and navigate to  https://hyperjumptech.github.io/monika-config-generator
