### ISSUE TITLE
Add options for monika to run agent in localhost or remote

### ISSUE THREAD

**Issue by ilmiawan** [hyperjumptech/monika#145]
**Describe the bug**
Currently monika only able to run from local agent, we want monika to also run from remote agent as in the symon original idea.
By running remote agent we can try multiple host or region for monitoring.

**To Reproduce**
1. Go to Monika
2. Add configuration
3. Run Monika

Currently the monitoring from Monika is only run from the local agent, checking the url set in probe. 

**Expected behavior**
Monika can run the checking to the url from agent deployed in remote servers.

**Comment by newm4n** [comment]
I have reconfirmed this issue with Pak @ariya , and my confirmation has a firm my stand on how we should do this technically. 
The explanation on how Monika should make a HTTP request call remotely is not by installing another monika instance remotely, making a monika to monika communication where one monika instruct another monika to make HTTP call. Instead, we are utilizing SSH communication to spawn CURL process on remote machine to do the HTTP call.

There are few reason why we should do the later approach. 

1. Making Monika to be able to "talk" to other monika is significantly more challenging compared to just simply execute other external process ( CURL ) using lots of SSH library.
2. CURL is much simpler, available on most (if not all) server in the world, and known to work.
3. CURL can do anything a HTTP client can do. 
4. Testing is much simpler, as we can easily simulate the remote calling (SSH) using CURL without the need to deploy anything remotely.
5. User do not have the burden of maintaining another remote app (e.g. remote monika server need to be maintained), If the remote curl is, less likely, to have problem, one can simply restart the server (or replace a simple VM).

**Comment by ariya** [comment]
An example config will be like the following:

```json
{
  "agents": [
    {
      "name": "Surabaya",
      "ip": "192.168.1.101",
      "username": "monika",
      "password": "trustno1"
    }
  ],
  "probes": [
    {
      "name": "Google",
      "description": "Check if Google is down or not",
      "interval": 60,
      "method": "GET",
      "timeout": 5,
      "requests": [
        {
          "url": "https://google.com"
        }
      ],
      "agents": [
        "local",
        "Surabaya"
      ]
    }
  ]
}
```

Here the probe named _Google_ will be executed on two places, _local_ (a special one) and _Surabaya_. The latter refers to the chosen agent name specified in the `agents` section.

The example illustrates the use username/password for authentication but obviously at some point we ought to support SSL certificate. Also for the time being, we can assume that the remote machine has cURL installed already.

**Comment by ariawan** [comment]
Isn't this feature supposed to be the job of symon? not monika?
