### ISSUE TITLE
New website: Create Button component

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#179]
## Requirements

Implement the following buttons:

- [ ] Gradient button
- [ ] Outline button
- [ ] Github button
- [ ] Star button

### Text

```css
font-family: IBM Plex Sans;
font-size: 16px;
font-style: normal;
font-weight: 600;
line-height: 21px;
letter-spacing: 0em;
text-align: center;
```

### Gradient button

![Property 1=Primary_Button](https://user-images.githubusercontent.com/311343/117309867-2040d280-ae83-11eb-92c2-448be71a7c8c.png)

```css
background: linear-gradient(86.29deg, #987CE8 4.96%, #2FDCDC 106.68%);
box-shadow: 0px 8px 25px rgba(64, 204, 221, 0.2);
border-radius: 24px;
```

### Outline button

![Property 1=Secondary_Button](https://user-images.githubusercontent.com/311343/117309884-26cf4a00-ae83-11eb-86cb-e523085ca76e.png)

Text:

```css
background: linear-gradient(86.29deg, #987CE8 4.96%, #2FDCDC 106.68%);
```

Outline:

```css
border: 2px solid;
border-image-source: linear-gradient(86.29deg, #987CE8 4.96%, #2FDCDC 106.68%);
box-shadow: 0px 8px 25px 0px #40CCDD33;
border-radius: 24px;
```

### Github button

![Property 1=Button With Icons](https://user-images.githubusercontent.com/311343/117309922-2e8eee80-ae83-11eb-8ff2-27c0643f2c6b.png)

### Star Button

![Property 1=Variant4](https://user-images.githubusercontent.com/311343/117309966-351d6600-ae83-11eb-9a68-116ca9c02c0e.png)

**Comment by samsunoor** [comment]
closed with #212
