### ISSUE TITLE
Show summary

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#189]
# Problem

There is no easy way to see the status of Monika. At this moment, we can only see what's happening from the log stream.

# Solution

- [x] Add a new flag `--status` to print out the status of currently running Monika.
- [x] When Monika is run with that flag, it should print out summary of the running process
   - [x] pid 
   - [x] Path to the configuration file (monika.json, config.json, or user defined configuration)
   - [x] Path to the database
   - [x] Number of probes
   - [x] Number of notifications
   - [x] Elapsed time
   - [ ] Average response time in the last 24 hours
   - [x] Number of incidents in the last 24 hours
   - [x] Number of recoveries in the last 24 hours
   - [x] Number of notifications in the last 24 hours.

**Comment by sapiderman** [comment]
Hmm having the config file it is running with should be usefule too I think.
