### ISSUE TITLE
Need to simplify Monika installation Process

### ISSUE THREAD

**Issue by ilmiawan** [hyperjumptech/monika#202]
**Describe the bug**
Currently Monika installation process other than docker, need also dependency to node js and run npm install first before running it. This becomes an obstacle for user who want to install monika. They are hindered by current installation instructions.
We would need to think of simplifying it to become only 1 `init` command, just to run monika wtih basic configuration settings. 
Need to consider also, the target user of Monika could be ops or QA that is not familiar with nodejs.

**Comment by nicnocquee** [comment]
Let's try https://oclif.io/docs/releasing#standalone-tarballs

**Comment by ariya** [comment]
Alternative: https://www.npmjs.com/package/pkg (used, among others, for the [Serverless framework](https://www.serverless.com/)).

**Comment by ariya** [comment]
Now tackled as part of #344.
