### ISSUE TITLE
High Severity Vulnerability Found in mailgun-js

### ISSUE THREAD

**Issue by haricnugraha** [hyperjumptech/monika#228]
**Describe the bug**
Vulnerability have been highlighted by npm audit in dependency of mailgun-js

**To Reproduce**
1. Run `npm audit`

**Expected behavior**
No vulnerabilities should be found.

**Screenshots**
![Screenshot from 2021-06-16 11-48-24](https://user-images.githubusercontent.com/15191978/122160023-6e40f100-ce99-11eb-96fa-6d54265e93eb.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Version [e.g. 20.04]

**Comment by sapiderman** [comment]
After some investigating the lib/package we are using is not maintained. We are using [mailgun-js v0.22.0](https://github.com/mailgun/mailgun-js-boland/releases) been fixed 0.23.0 in 2020 january, but never pushed to npm. Highly recommend that we chagne package.

![image](https://user-images.githubusercontent.com/964106/127854767-861bbcc6-2aad-4469-9cc6-8035aaa1be50.png)
