### ISSUE TITLE
Probe detection record

### ISSUE THREAD

**Issue by newm4n** [hyperjumptech/monika#23]
Right now, for each of probe http call, the status and information is not recorded.
Thus is not possible to trace in historical manner of events and not able to see  to se trends in graphs fashion.

We need to save probe detection information which saves minimum.

1. Probe Name / ID
2. Time stamp
3. HttpRequest status (success or fail)
4. Response code
5. Response time

**Comment by nicnocquee** [comment]
So that Monika is more flexible, 

- [ ] Add a flag to specify the directory to put the SQLite database file.
