### ISSUE TITLE
Exception when probe returns from Incident

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#230]
**Describe the bug**

Unhandled exception when coming back from incident.

**To Reproduce**
1. Need to use multiple url, for instance to local host.

  ```
    "requests": [
        {
          "method": "GET",
          "url": "http://localhost:7001/health",
          "saveBody": false
        },
        {
          "method": "GET",
          "url": "http://localhost:7001/v1/hello",
          "saveBody": false
        }
      ],
```

2. Make the target inaccesible:
3. After incident notification "NOTIFY-INCIDENT" make the target available:
4. The following error in the logs (on ver 1.3.1):

![image](https://user-images.githubusercontent.com/964106/122202254-115c2f80-cec7-11eb-8cfe-afbd73501ee7.png)

**Expected behavior**
1. Should not result in an error

**Comment by nicnocquee** [comment]
I cannot reproduce this in v1.3.7. Have you tried?

**Comment by sapiderman** [comment]
yes on the 1.3.7 too... 

![image](https://user-images.githubusercontent.com/964106/122386569-379dd000-cf98-11eb-993d-22187c03c33f.png)
