### ISSUE TITLE
validate response, send notification and store to db should be out of looper

### ISSUE THREAD

**Issue by ilmiawan** [hyperjumptech/monika#242]
As part of our plan to refactor Monika, we need to take out  validate response, send notification and store to db from looper.

<img width="849" alt="Screen Shot 2021-06-30 at 13 52 58" src="https://user-images.githubusercontent.com/8952493/123915342-986ed480-d9aa-11eb-811a-47fcbf4db7b8.png">

**Comment by kevinhermawan** [comment]
This ticket is so big and mostly critical, I will separate this ticket into small PRs.

- [ ] Refactor validate response
- [ ] Refactor send notification
- [ ] Refactor store to db
