### ISSUE TITLE
Generate monika.json from a HAR file

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#282]
Following up issue #274 , Monika should be able to generate a `monika.json` file from a HAR file by running

```
monika --create-config --har <path_to_har_file>
```

Note that Monika already has `--create-config` flag which will open our Config Generator in the browser. When this flag is combined with `--har` flag, it should just create a valid configuration file without running it.

**Comment by ilmiawan** [comment]
@nicnocquee --create-config flag is already being used for opening config-generator web:
```
if (flags['create-config']) {
      log.info(
        'Opening Monika Configuration Generator in your default browser...'
      )
      await open('https://hyperjumptech.github.io/monika-config-generator/')
      return
    }```

**Comment by nicnocquee** [comment]
Yes, but when `--create-config` flag is accompanied with `--har`, it should generate monika.json from the har file instead. When it's just `--create-config` by itself, it should open the monika config generator.
