### ISSUE TITLE
REGRESSION: Monika not reloading when file changes

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#300]
**Describe the bug**
Monika does not automatically use recent configuration file local file.

**To Reproduce**
1. Run monika from local config
2. Make some changes to the configuration file.
3. Monika keeps using the old configuration

**Expected behavior**
Monika should reload using the new configuration file.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.4.1

**Comment by armedi** [comment]
Can you share the config being used and the changes made?

I can't reproduce this bug in my machine with the config that I use.

**Comment by nicnocquee** [comment]
never mind, it works again now, I probably saved the wrong config lol
