### ISSUE TITLE
Improve Alert/Notification messages sent to channels

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#303]
Improve the notification messages that is sent from Monika

It should contain: 
1. The type of error/notification 
2. And what specifically caused the notification

The following is the present notification:
![image](https://user-images.githubusercontent.com/964106/127263204-bec71f94-427c-47e5-99c9-8efaf6651d92.png)

It's a bit repetitive, and missing some info; what was the error code that triggered the not-2xx? 
Change time to "At". Time is the notification or the email? At is a definite when.

A better notifications might be:
  
Monika is running on LOCAL_IP_ADDRESS (local), PUBLIC_IP_ADDRESS (public), HOSTNAME (hostname).

Monika is terminated on LOCAL_IP_ADDRESS (local), PUBLIC_IP_ADDRESS (public), HOSTNAME (hostname).

**New Incident from Monika**

* Alert :  Status is **500**, was expecting **200**
* url : http://api.example.com/
* At : 2021-07-28 , 13:30:30
* Monika: LOCAL_IP_ADDRESS (local), PUBLIC_IP_ADDRESS (public), HOSTNAME (hostname)
  

**New Incident from Monika**

* Alert : Response time is  **700ms** expecting a **200ms**
* url : http://api.example.com/
* At : 2021-07-28 , 13:30:30
* Monika: LOCAL_IP_ADDRESS (local), PUBLIC_IP_ADDRESS (public), HOSTNAME (hostname)

**New Recovery from Monika**

* Alert : Service is ok. Status now **200** was **401**
* url : http://api.example.com/
* At : 2021-07-28 , 13:30:30
* Monika: LOCAL_IP_ADDRESS (local), PUBLIC_IP_ADDRESS (public), HOSTNAME (hostname)
  

**New Recovery from Monika**

* Alert : Service is ok. Response now is within **50ms**
* url : http://api.example.com/
* At : 2021-07-28 , 13:30:30
* Monika: LOCAL_IP_ADDRESS (local), PUBLIC_IP_ADDRESS (public), HOSTNAME (hostname)

When public ip cannot be determined, don't include it, just use the local ip address and hostname.

**Comment by nicnocquee** [comment]
You can get the public IP address using this https://github.com/sindresorhus/public-ip#readme
