### ISSUE TITLE
Current configuration is forecebily overwritten

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#306]
When using `--create-config` with `--har` the existing monika.json file that was lovingly crafted is overwritten without any warning.

Overwritting files without any warning or confirmation is not a good user experience.

Bring my file back!

**Comment by nicnocquee** [comment]
Correct. Needs a fix:

- [ ] If the output file exists, abort the config generation and show warning: `Cannot write configuration file to ${output} because file already exists. Use --force to overwrite.`
- [ ] If the output file exists, and `--force` flag is used, overwrite the file.
