### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#42]
An error could be from the probe, or from attempt to create notification.

It would be good to have indication on where the error is from.

**Comment by nicnocquee** [comment]
The errors should be categorized into:

1. Validation errors. These errors occur at the beginning of the application when the configuration file is validated.
2. Probing errors. These errors occur when the target URLs are probed.
3. Alert errors. These errors occur when notifications are sent. 
4. Data storing error. These errors occur when the probing result is stored to database.

**Comment by sapiderman** [comment]
Thinking also to create a common API and some standard for everyone to use.  Maybe something like
displayInfo( module, msg )
displayError( module, msg )
Then formatting should all be uniform. thoughts?

**Comment by nicnocquee** [comment]
we can use [winston](https://github.com/winstonjs/winston)

**Comment by nicnocquee** [comment]
Continue in #56
