### ISSUE TITLE
Wrong recovery message

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#423]
The recovery message should be:

"Target is back to healthy. The response time is less than xxx"

![IMG_E49725B678C9-1](https://user-images.githubusercontent.com/311343/133797926-0bc73189-e077-4228-bec4-b7545bb75394.jpeg)

**Info**

Monika v1.6.0
@hyperjumptech/monika/1.6.0 linux-x64 node-v10.15.0

**Comment by armedi** [comment]
Can you provide the config used?

I think in the 1.6.0 version, for the default `response-time-greater-than-2-s` the message should be https://github.com/hyperjumptech/monika/blob/5881fd3461beb588df07c1474ef32d7e50e41eea/src/components/config/validate.ts#L300

**Comment by nicnocquee** [comment]
ah nvm. It's because I have 'message' in the alerts.
