### ISSUE TITLE
Add Auto Install Script in UNIX Installation

### ISSUE THREAD

**Issue by dennypradipta** [hyperjumptech/monika#455]
**Describe the issue**
In [Volta Getting Started](https://docs.volta.sh/guide/getting-started) page, it is said that it could be installed using CURL. We want to be able to create an installation flow like so, so that user without NPM installed can run Monika straight away.
![image](https://user-images.githubusercontent.com/16670475/135552908-5a6413a9-6757-43e9-80cf-b560e4a9ba5c.png)

**Expected behavior**
With a single CURL such as `https://monika.hyperjump.tech/get | bash`, we can install Monika.
The script should be:
1. Detect the operating system (Linux/MacOS)
2. Download the latest file from the release page according to their OS [https://github.com/hyperjumptech/monika/releases](https://github.com/hyperjumptech/monika/releases)
3. Extract the file, ask for sudo permissions to copy it to the /usr/local/bin
4. Update bash/zsh/fish startup file so that user can run `monika` later without having to modify the bashrc/zshrc/fishrc file
5. Confirm by running `monika -v`

**Additional context**
- Our website is https://monika.hyperjump.tech and we serve the page from the /docs folder using Github Pages. So if you want to add the endpoint for /get page, modify the contents of the /docs.

**Comment by npalladium** [comment]
I've looked at voltas install script and would love to help out with this.

**Comment by sapiderman** [comment]
> I've looked at voltas install script and would love to help out with this.

@npalladium grab the ticket... it's all yours!

**Comment by dennypradipta** [comment]
I've assigned the issue to you @npalladium you can start your work :smile:

**Comment by dennypradipta** [comment]
Hi @npalladium how is it going? Do you have problems while working on this issue?
