### ISSUE TITLE
url when "error config file not found" is wrong

### ISSUE THREAD

**Issue by ariawan** [hyperjumptech/monika#46]
**Describe the bug**
url when "error config file not found" is wrong

**To Reproduce**
1. Install monika with `$ npm i -g @hyperjumptech/monika`
2. Run monika with `$ monika`
3. see error:  
    ```
    Error: Config file not found! Copy example config from 
    https://github.com/hyperjumptech/monika/blob/main/config.json.example
    ```

**Expected behavior**
the url should be `https://github.com/hyperjumptech/monika/blob/main/config.example.json`

**Comment by nicnocquee** [comment]
Already fixed in PR #29
