### ISSUE TITLE
Header value only set once in chaining request

### ISSUE THREAD

**Issue by ilmiawan** [hyperjumptech/monika#461]
**Describe the bug**
Header value only set once in chaining request, it didn't changed while running the next loop of chain request.

**To Reproduce**
1. Go to monika.yml and set probe with chaining request
2. Set next request header from value of the first request response
3. Check the next request header value from 2nd, 3rd, ... loop 
4. it should be set from the first request value in the same loop, not from the first loop.

**Expected behavior**
The header value on the next loop should be set from the first request of the same loop, not from the value of the first loop.

**Desktop (please complete the following information):**
 - OS: [Mac Os, Ubuntu]
 - Version [11.6, 18.04]

**Comment by dennypradipta** [comment]
Isn't this already solved in the #384 ?

**Comment by nicnocquee** [comment]
Solved in #472
