### ISSUE TITLE
Update Documentation for Running Monika with Docker

### ISSUE THREAD

**Issue by dennypradipta** [hyperjumptech/monika#486]
# Previously in Monika Discussion:

### Discussed in https://github.com/hyperjumptech/monika/discussions/485

<div type='discussions-op-text'>

<sup>Originally posted by **heriy89** October 15, 2021</sup>
Hello, I'm a newbie 😃.
I previously tried this script from the tutorial on [medium.com](https://medium.com/hyperjump-tech/collecting-monika-with-prometheus-9faa7d484a30), but I got an error "**unknown flag: --prometheus**". After I checked, in the docker command, there's no **--prometheus** command. How to running Monika - Prometheus with docker command? Is there any other solution? 😺  Thanks before.

Here's I run this command:
```
docker run --name monika \
    -p 3001:3001 \
    -v ${PWD}/monika.json:/config/monika.json \
    --prometheus 3001 \
    --detach hyperjump/monika:latest
```
</div>

It seems that the documentation for running Monika with Docker in the Documentation page is unclear. I think we should update the documentation and explain how to run Monika using Docker, either run it on foreground or background.

In the discussion page, I already made an example on how to run it. 

## Additional Context

The documentation is located in the /docs folder. Take a look around and update the documentation for "Run Monika using Docker" section.

**Comment by saravananselvamohan** [comment]
@dennypradipta Would like to take up the issue

**Comment by saravananselvamohan** [comment]
@dennypradipta Please give few commands to make Monika up and running in some port using Docker. I am bit struggling to achieve this.

**Comment by dennypradipta** [comment]
Hi, basically Monika does not run any port except when there is a `—prometheus` flag enabled.

You can run monika with just `monika`, which will be looking for monika.yml by default.

If you want to choose another config file, you can use `monika -c <path_to_config>`

The rest can be found in the CLI Options documentation which you can find in https://monika.hyperjump.tech/docs

Good luck!

**Comment by dennypradipta** [comment]
Hello @saravananselvamohan how's it going? Do you have any trouble while working on this?

If you decide to not continue your work, I will unassign you from this issue. Let me know :grinning:

**Comment by saravananselvamohan** [comment]
@dennypradipta Please reassign
