### ISSUE TITLE
Update alert documentation

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#497]
To make it clearer, the [alert documentation](https://monika.hyperjump.tech/guides/alerts) needs to be updated:

- [x] The units of response time. Is it millisecond, or seconds?
- [x] An example of the YAML configuration to use the helper functions such as `lowerCase()`, etc.
- [x] Fix wrong yml syntax for the array

**Comment by sapiderman** [comment]
merged in #525
