### ISSUE TITLE
error message enhancement

### ISSUE THREAD

**Issue by ariawan** [hyperjumptech/monika#50]
When I try to run monika using `config.example.json`, without changing anything. I got non-descriptive error message `Method not found`

I know I am not supposed to do that, but it would be nice, if the error message would be more descriptive.

![-bash_and_Client_Pipeline__Hyperjump____Microsoft_Teams](https://user-images.githubusercontent.com/230018/111565276-a6b72d00-87cd-11eb-884e-ceb7570639be.jpg)

**Comment by nicnocquee** [comment]
Fixed in v1.0.1. But we need to improve all log and error messages.
