### ISSUE TITLE
Doc still mentions monika.json even though the example is in yml now

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#522]
**Describe the bug**
There are still many mentions of `monika.json` even though the doc is showing yml example now.

**To Reproduce**
1. Go to https://monika.hyperjump.tech/guides/probes
2. See there are many mentions of monika.json

**Expected behavior**
It should say monika.yml.

**Screenshots**
<img width="1377" alt="Screenshot 2021-11-06 at 01 23 20" src="https://user-images.githubusercontent.com/311343/140591364-e142167e-e4f2-457a-91d0-573c91381b4a.png">

**Comment by sapiderman** [comment]
merged in: https://github.com/hyperjumptech/monika/pull/524
