### ISSUE TITLE
Config example needs to work out-of-the-box

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#53]
## Issue: Example config does not run without error

For best user experience, the config.json.example should work out of the box without error
Including:

1. notifications
2. probe target
3. alerts
4. intervals

update notifications documents also, according to the new config.json.example

**Comment by nicnocquee** [comment]
I think the only way an example config works out of the box is if the config only contains webhook notification which points to a server we maintain. 

An idea to make Monika works _almost_ out of the box is to have multiple config examples where each of the example only contains single notification:

`config.smtp.gmail.example.json`: contains an `smtp` notification configuration as follows

```json
  "notifications": [
    {
      "id": "unique-id-smtp",
      "type": "smtp",
      "data": {
        "recipients": ["ENTER_YOUR_EMAIL_ADDRESS_HERE"],
        "hostname": "smtp.gmail.com",
        "port": 587,
        "username": "ENTER_YOUR_GMAIL_ADDRESS_HERE",
        "password": "ENTER_YOUR_GMAIL_PASSWORD_OR_APP_PASSWORD_IF_2FA_ACTIVE"
      }
    }
  ]
```

`config.sendgrid.example.json`: contains a `sendgrid` notification configuration as follows

```json
{
       "id": "unique-id",
       "type": "sendgrid",
       "data": {
         "recipients": ["ENTER_YOUR_EMAIL_ADDRESS_HERE"],
         "apiKey": "GET_API_KEY_FROM_SENDGRID"
       }
     }
```

And so on.
