### ISSUE TITLE
Improve log messages

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#56]
Right now Monika spits out too many log messages. 

To do:

- [ ] Reduce log messages, only show important messages:
       
     1. When Monika starts, logs the number of probes and the number of notifications. E.g., `Starting Monika. Probes: 3. Notifications: 2.`
     2. When probing, shows current time, probe id, URL, and method.
     3. When probe finishes, shows response status and response time.
     4. When alert is triggered but still under threshold, prints out for example, `status-not-2xx triggered 1 time in a row (threshold: 3). Notifications are not sent yet.`
     5. When the alert is triggered multiple times in a row more than the threshold, prints out for example, `status-not-2xx triggered 3 times in a row (threshold: 3). Notifications will be sent.`
     6. When the notification is sent, print out for example `Notification for status-not-2xx is sent via notification_id (SMTP).`
     7. When the alert is still triggered but the notification has been sent, print out for example `status-not-2xx triggered 4 times in a row (threshold: 3). Notifications has been sent.` 
     8. When the URL recovers from the alert and the notification is sent, print out for example `Notification for status-not-2xx recovery is sent via notification_id (SMTP)`.
       
- [ ] Add a `--verbose` flag to show verbose log messages.

    1. Shows the detail of the probe, except API_KEY and password if any.
    2. Shows the detail of the notification configuration when the notification is sent except any API_KEY and password.

**Comment by nicnocquee** [comment]
Formatting proposal for the compact logging:

## Probing log

Print out the following info message when Monika finishes probing a URL.

```
<DATE>,PROBE,<CHECK_ORDER>,<PROBE_ID>,<PROBE_URL>,<STATUS_CODE>,<RESPONSE_TIME>
```

Example:

```
2021-03-21T20:35:12.233Z,PROBE,2,1,http://localhost:5000,200,0.1
```

## Alert log

Print out the following info message when an alert is triggered.

```
<DATE>,ALERT,<ALERT_TYPE>,<CONSECUTIVE_TRUE>,<CHECK_ORDER>,<PROBE_ID>,<PROBE_URL>,<STATUS_CODE>,<RESPONSE_TIME>
```

Example:

```
2021-03-21T20:35:12.233Z,ALERT,status-not-2xx,1,2,1,http://localhost:5000,200,0.1
```

## Notification log

Print out the following info message when a notification is sent out.

When Monika notifies an incident: (e.g., status code 500 3 times in a row)

```
<DATE>,NOTIFY-INCIDENT,<ALERT_TYPE>,<NOTIFICATION_TYPE>,<NOTIFICATION_ID>,<PROBE_ID>,<PROBE_URL>
```

When Monika notifies that the URL recovers from the incident: (e.g., status code 200 3 times in row after 500 status code)

```
<DATE>,NOTIFY-RECOVER,<ALERT_TYPE>,<NOTIFICATION_TYPE>,<NOTIFICATION_ID>,<PROBE_ID>,<PROBE_URL>
```

Example

```
2021-03-21T20:35:18.244Z,NOTIFY,status-not-2xx,smtp,notification_id,1,http://localhost:5000
```

## Combined logs

```
2021-03-21T20:35:09.232Z,ALERT,status-not-2xx,1,1,1,http://localhost:5000
2021-03-21T20:35:09.235Z,ALERT,status-not-2xx,2,1,2,https://hyperjump.tech
2021-03-21T20:35:12.233Z,PROBE,2,1,http://localhost:5000,200,0.1
2021-03-21T20:35:12.234Z,PROBE,2,2,https://hyperjump.tech,200,0.1
2021-03-21T20:35:15.239Z,PROBE,3,1,http://localhost:5000,200,0.1
2021-03-21T20:35:15.240Z,PROBE,3,2,https://hyperjump.tech,200,0.1
2021-03-21T20:35:18.244Z,NOTIFY-INCIDENT,status-not-2xx,smtp,notification_id,1,http://localhost:5000
```

**Comment by nicnocquee** [comment]
Related to issue #42. Better to decide to use winston or not.

**Comment by sapiderman** [comment]
suggestion, status code first then URL. Since it's easier to scan status code. Also aligns better visually.

<DATE>,PROBE,<CHECK_ORDER>,<PROBE_ID>,<**STATUS_CODE**><PROBE_URL>,<RESPONSE_TIME>
