### ISSUE TITLE
Create deployment pipeline for Brew

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#584]
For mac users, it's pretty common to use brew to install apps. It'd be great if we could just `brew install monika`

**Comment by raosan** [comment]
- [x] Upload package to [homebrew core repo](https://github.com/Homebrew/homebrew-core)
- [x] package accepted, can be downloaded by `brew install monika`
- [ ] update docs: how to install with brew
- [ ] create deployment pipeline inn github actions
