### ISSUE TITLE
Install monika via Chocolatey

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#585]
For Windows users, it'd be cool to be able to install Monika via [Chocolatey](https://chocolatey.org/).

**Comment by raosan** [comment]
- [x] Upload package to registry
- [ ] package reviewed
- [x] package still can be download even though the package not reviewed by `choco install monika --version=1.6.11`
- [ ] update readme: how to install with chocolatey
- [ ] create CI/CD
