### ISSUE TITLE
Create a sample config when running Monika without a config

### ISSUE THREAD

**Issue by dennypradipta** [hyperjumptech/monika#624]
Currently, if you run Monika but `monika.yml` does not exist, it will tell you that "Configuration file not found". 

I think we need to create a sample YAML file when users try to run Monika without any configuration available.

For example, if we are running `monika` without any `monika.yml` in the relative path:
```bash
$ monika

No Monika configuration available, initializing...
monika.yml file has been created in this directory. Change the URL in the probe section to your URL.

$ monika

Monika is running..............
```

As for the default configuration, we can use [monika.example.yml](https://github.com/hyperjumptech/monika/blob/main/monika.example.yml) from the repository. Also we need to add links to the Monika Config Generator in the example configuration

**Comment by nicnocquee** [comment]
Closed via #654
