### ISSUE TITLE
Change notification in smtp to text and time to be known

### ISSUE THREAD

**Issue by ilmiawan** [hyperjumptech/monika#63]
**Describe the bug**
1. Currently the smtp notification set as html, therefore there is no formatting and become one line.
2. The time in notification is sent as unix format, not readable to human. 

**To Reproduce**
1. Set smtp config.json 
2. Run monika
3. Wait for notification firing
4. see the notification sent

**Expected behavior**
1. [x] the notifications sent as text.
2. [x] the time in notifications to be readable by human

**Comment by nicnocquee** [comment]
I think we need to define the messaging for each of the alerts:

## status-not-2xx

On incident:

- title/subject: `[INCIDENT] Target URL is not OK`
- message: 
   ```
   Target $url is not healthy. It has not been returning status code 2xx $threshold times in a row.

   Alert: status-not-2xx
   Source: IP Address, $location_name
   Date: $date
   ```
   Example
    ```
   Target https://hyperjump.tech is not healthy. It has not been returning status code 2xx 5 times in a row.

   Alert: status-not-2xx
   Source: 192.168.1.1, Jakarta
   Date: Monday, 1 Jan 1970 18:00
   ```

On recovery:

- title/subject: `[RECOVERY] Target URL is not OK`
- message: 
   ```
   Target $url is back to healthy. 

   Alert: status-not-2xx
   Source: IP Address, $location_name
   Date: $date
   ```
   Example
    ```
   Target https://hyperjump.tech is back to healthy.

   Alert: status-not-2xx
   Source: 192.168.1.1, Jakarta
   Date: Monday, 1 Jan 1970 18:00
   ```

## response-time-greater-than-x-s

On incident:

- title/subject: `[INCIDENT] Target URL takes long to respond`
- message: 
   ```
   Target $url is not healthy. The response time has been greater than $time $threshold times in a row.

   Alert: response-time-greater-than-3-s
   Source: IP Address, $location_name
   Date: $date
   ```
   Example
    ```
   Target https://hyperjump.tech is not healthy. The response time has been greater than 3 seconds 5 times in a row.

   Alert: response-time-greater-than-3-s
   Source: 192.168.1.1, Jakarta
   Date: Monday, 1 Jan 1970 18:00
   ```

On recovery:

- title/subject: `[RECOVERY] Target URL takes long to respond`
- message: 
   ```
   Target $url is back to healthy.

   Alert: response-time-greater-than-3-s
   Source: IP Address, $location_name
   Date: $date
   ```
   Example
    ```
   Target https://hyperjump.tech is back to healthy.

   Alert: response-time-greater-than-3-s
   Source: 192.168.1.1, Jakarta
   Date: Monday, 1 Jan 1970 18:00
   ```
