### ISSUE TITLE
cli-ux@5.6.7: Package no longer supported

### ISSUE THREAD

**Issue by aryegogo** [hyperjumptech/monika#634]
There is an error when install monika.
sudo npm i -g @hyperjumptech/monika

npm WARN deprecated cli-ux@5.6.7: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

![image](https://user-images.githubusercontent.com/95399152/160336227-54acfce4-e964-4847-9be9-383f032883f0.png)

**Comment by nicnocquee** [comment]
Hello @aryegogo, that doesn't seem like error, only warnings. But can you share what OS and node version you used?

**Comment by aryegogo** [comment]
OS ubuntu 20.04
Node 14.18.2
