### ISSUE TITLE
Show table of contents in every page in docs

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#647]
It'd be great to be able to see what sections in a page there are and to jump to certain section quickly. We need to have a table of content on the right side of the page, such as the one in [Remix docs](https://remix.run/docs/en/v1/tutorials/blog). 

<img width="1288" alt="Screenshot 2022-04-14 at 09 13 59" src="https://user-images.githubusercontent.com/311343/163334126-a0e25599-ee89-45a7-b22a-b166b0e78f9c.png">

**Comment by lukman7788** [comment]
https://github.com/hyperjumptech/monika/pull/651
