### ISSUE TITLE
statusText is not returned from the response.

### ISSUE THREAD

**Issue by FStorm87** [hyperjumptech/monika#650]
When checking the url, I can get the statuscode (`{{ response.status }}`). But statustext (`{{ response.statusText }}`) is returned empty
Screenshot:
<img width="370" alt="Снимок экрана 2022-04-18 в 11 06 36" src="https://user-images.githubusercontent.com/26481726/163778014-30c2bf43-c53b-4f42-8c1d-88f48b4ca473.png">

**Comment by haricnugraha** [comment]
As written in the [latest documentation](https://monika.hyperjump.tech/guides/alerts#alert-query). Currently, only these values are available:
- response.status: HTTP status code of the reponse
- response.time: the time it takes to perform a HTTP request
- response.size: size of the response in bytes
- response.headers: HTTP response headers
- response.body: HTTP response body (if content-type is JSON, it will be parsed automatically)
