### ISSUE TITLE
Standalone Monika binary for Windows couldn't find the monika.yml in the same folder 

### ISSUE THREAD

**Issue by dennypradipta** [hyperjumptech/monika#652]
**Describe the bug**
Monika couldn't seem to find the monika.yml in the same folder as the standalone Monika binary downloaded from the Github Release Page.

**To Reproduce**
1. Download Monika for Windows from the Github Release Page
2. Extract the zip
3. Create a monika.yml configuration (use this [https://gist.github.com/dennypradipta/b4ffe76281be2f0aa676ff6d8f87108c](https://gist.github.com/dennypradipta/b4ffe76281be2f0aa676ff6d8f87108c))
4. Save the file in the same folder with the extracted Monika binary
5. Open PowerShell in the current folder and run `.\monika`

**Expected behavior**
It should read the monika.yml in the same folder 

**Screenshots**
![image](https://user-images.githubusercontent.com/16670475/163923020-b5b115c8-cf11-41eb-a024-934cf1014b62.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**

**Comment by sapiderman** [comment]
confirmed running `.\monika` only gets this error
On Win11 powershell
On Win11 using regular `cmd.exe` console also

**Comment by nicnocquee** [comment]
Try again with latest from `main`.

**Comment by raosan** [comment]
fixed in `main`
