### ISSUE TITLE
Improve project structure

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#66]
As features and project is growing, coimplexity and features are increasing.

1. Need to update the project structure 
2. Not put everything in utils/

To improve collaboration, minimize conflicts.
Improve SOLID and scalability.

**Comment by haricnugraha** [comment]
Looks like this is duplicate of #26.

**Comment by sapiderman** [comment]
@haricnugraha it's similar, but different. One is physical layout of the project itself. The other is architectural design.
But closing this and have project layout similar to design as in #26
