### ISSUE TITLE
Update docker.hub with better information

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#667]
The [hub.docker](https://hub.docker.com/r/hyperjump/monika) is rather bare, and needs a little love.

1. Add some basic overview
2. Link to our docs or github site for further information

![image](https://user-images.githubusercontent.com/964106/169492560-d6b065cf-00ee-4a6f-95e9-043566c61126.png)

**Comment by nicnocquee** [comment]
Fixed by @newm4n
