### ISSUE TITLE
Docs: layout for Macbook Pro 13"

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#702]
## Bug description

When opening the docs pages in Safari, Chrome, or even Firefox in a Macbook Pro 13" macOS 12.4, the table of contents is not placed on the right side of the docs, it's in the top instead.

<img width="1552" alt="Screenshot 2022-06-14 at 14 26 58" src="https://user-images.githubusercontent.com/311343/173577036-c13a015c-850b-4919-b80e-9841071dfc1c.png">

## Expectation

The ToC should still show up on the right side of the page. 

## Note

- the width of the body is 1425 pixel.
- seems like the correct layout appears when the width is 1536 pixel.

**Comment by arifath** [comment]
helo, can i help fix this?
