### ISSUE TITLE
Docker container wont run due to: Failed to obtain location/ISP info. Got: Error: stun inaccessible

### ISSUE THREAD

**Issue by rgraham7503** [hyperjumptech/monika#708]
I am running this command (docker run --name monika -v /Monika_Monitor/full_monitor_monika.yml:/config/monika.yml -it hyperjump/monika:latest) as per documentation, and getting the below error:

WARN: Failed to obtain location/ISP info. Got: Error: stun inaccessible

(node:1) UnhandledPromiseRejectionWarning: Error: Configuration file not found: /config/monika.json.

    at Object.error (/usr/local/lib/node_modules/@hyperjumptech/monika/node_modules/@oclif/core/lib/errors/index.js:29:15)

    at Monika.error (/usr/local/lib/node_modules/@hyperjumptech/monika/node_modules/@oclif/core/lib/command.js:90:23)

    at Monika.run (/usr/local/lib/node_modules/@hyperjumptech/monika/lib/index.js:193:18)

    at async Monika._run (/usr/local/lib/node_modules/@hyperjumptech/monika/node_modules/@oclif/core/lib/command.js:67:22)

(Use `node --trace-warnings ...` to show where the warning was created)

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

 ›   Error: Configuration file not found: /config/monika.json.

**Comment by sapiderman** [comment]
@rgraham7503 thanks for the report.
just as a followup question... if you run without docker on the same environment, are you able to connect to stun server?
run `monika -c full_monitor_monika.yml`

also can you please let us know what version of monika you are using? `monika -v`

**Comment by rgraham7503** [comment]
No I can run it with npm and it works fine on same host. I'm guessing this is due to docker networking?

**Comment by sapiderman** [comment]
hi @rgraham7503 

1. First the failed ISP/location is really just a warning, so should not be fatal. The container can't resolve the STUN server we're trying to lookup;
Fix: Add the `--net=host` when creating your container. It will use the host network config

2. What made it fail is were looking for `/config/monika.json` in the container, which it can't find.
Fix: Copy the config file into the container: `docker container cp monika.json your_container_name:/config`

That should do it.

We're updating the Dockerfile and documentation to fix this.
