### ISSUE TITLE
Monika installed from Snap fails to run

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#801]
**Describe the bug**
Monika run from snapd is missing EACCESS to '/etc/lsb-release'

**To Reproduce**
1. Install monika with snap `sudo snap install monika`
2. Run monika  directly by typing: `monika`

**Expected behavior**
Monika should run

**Screenshots**
![image](https://user-images.githubusercontent.com/964106/180372842-5a94026f-c88e-42a6-ba0b-1d276a11ae07.png)

**Environment:**
 - OS: Linux 
 - OS Release: 22.04
 - Distro: Pop!_OS 22.04 LTS jammy 
 - Monika Version:  1.9.1, 1.9.3, 1.10.0
 
**Additional context**
`monika -h` works
`monika -v` works

**Comment by dennypradipta** [comment]
Tried to use Monika v1.11.0 using Snap, works as intended:
![image](https://user-images.githubusercontent.com/16670475/184284163-107c7e72-1639-4b3f-bba2-d66ea5b9f0bc.png)

Could you provide your `snap connections monika` and `snap interfaces monika` like below?:
![image](https://user-images.githubusercontent.com/16670475/184284296-a802a2cd-7677-4acf-b7d2-635b833c1d03.png)
