### ISSUE TITLE
Wrong schema for timeout in JSON schema

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#804]
The `timeout` property we use corresponds to axios' timeout which is in milliseconds. See [here](https://github.com/axios/axios#request-config). So the default must be `10000`. Also needs to mention that it's in milliseconds.

<img width="728" alt="Screenshot 2022-07-22 at 09 07 35" src="https://user-images.githubusercontent.com/311343/180383953-c28149f5-12bb-41eb-a3c6-078cf0f86d6f.png">

**Comment by sapiderman** [comment]
Closing... merged in #820
