### ISSUE TITLE
Investigate worker threads

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#827]
I think there's a chance to improve Monika's performance by using worker threads for each probes especially with a large number of probes.

Reference:
- https://deepsource.io/blog/nodejs-worker-threads/
- https://blog.logrocket.com/node-js-multithreading-worker-threads-why-they-matter/

**Comment by dennypradipta** [comment]
I'll be taking up this issue.

**Comment by dennypradipta** [comment]
Closed by #972
