### ISSUE TITLE
Setup mocking library using Sinon.js

### ISSUE THREAD

**Issue by kevinhermawan** [hyperjumptech/monika#88]
# Summary

Currently Monika doesn't have a mocking library for testing. I recommend to install and setup Sinon.js as a mocking library

**Comment by armedi** [comment]
It already has chai-spies. Although it is not as powerful as Sinon, I think it is sufficient for our use case.
Or should we change to Sinon?

reference: [https://www.chaijs.com/plugins/chai-spies/](https://www.chaijs.com/plugins/chai-spies/)

**Comment by kevinhermawan** [comment]
I've been seen the reference, yes I think `chai-spies` is enough in the current use case, thanks!
