### ISSUE TITLE
HTTP request has no timeout

### ISSUE THREAD

**Issue by haricnugraha** [hyperjumptech/monika#907]
**Describe the bug**
Currently, the HTTP request made by Monika has no timeout. It might make the request stale and use resources inefficiently. It would be better if we add a timeout, so that if the server is not responding, Monika will drop the request. More Info: https://github.com/axios/axios/blob/main/README.md#request-config.
![image](https://user-images.githubusercontent.com/15191978/193765063-2b8ec3bd-6f74-433f-87af-c66a692ae8c7.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/15191978/193763690-cc38162e-9feb-48e4-933d-d10ec5402d14.png)
![image](https://user-images.githubusercontent.com/15191978/193763760-7f4c42fa-57b4-4ae1-91b1-44fa5420e780.png)
![image](https://user-images.githubusercontent.com/15191978/193763849-c9190bba-c29f-4663-9e9f-cf76c2add9b8.png)
![image](https://user-images.githubusercontent.com/15191978/193763927-4dd32e4c-1aa3-4d8b-9751-2273747d400f.png)

**Comment by sapiderman** [comment]
You mean, add a default timeout?

**Comment by haricnugraha** [comment]
> You mean, add a default timeout?

Yeah. We need to create a default timeout for it.
